name: Nightly

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Assemble with Gradle
        run: ./gradlew -PcommitCount=$(git rev-list --count master) -PcommitHash=$(git rev-parse --short master) -PstorePassword="${{ secrets.NIGHTLY_KEYSTORE_PASSWORD }}" -PkeyPassword="${{ secrets.NIGHTLY_KEYSTORE_PASSWORD }}" assembleNightlySigned
      - name: Delete existing nightly tag
        run: git push origin --delete nightly || true
      - name: Delete existing nightly release
        run: |
          TAG_NAME=nightly
          
          # Fetch the release associated with the tag
          RESPONSE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/releases/tags/$TAG_NAME")

          # Check if a release was found
          RELEASE_ID=$(echo "$RESPONSE" | jq -r ".id")

          if [[ "$RELEASE_ID" == "null" || -z "$RELEASE_ID" ]]; then
            echo "No release found for tag: $TAG_NAME"
          else
            echo "Deleting release with ID: $RELEASE_ID"
            curl -s -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/$REPO/releases/$RELEASE_ID"
          fi
          
          # Delete the tag.
          RESPONSE=$(curl -s -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/git/refs/tags/$TAG_NAME")

          # Check for success
          if echo "$RESPONSE" | grep -q '"message":'; then
            echo "Error: $(echo "$RESPONSE" | jq -r '.message')"
          else
            echo "Tag '$TAG_NAME' deleted successfully."
          fi
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            authenticator/build/outputs/apk/nightly/signed/authenticator-nightly-signed.apk
            companion/build/outputs/apk/nightly/signed/companion-nightly-signed.apk
          name: Nightly Release
          tag_name: nightly
          body: |
            Nightly build for commit ${{ github.sha }}.
          draft: false
          prerelease: true


